# Generated by Django 5.2.5 on 2025-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_call_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='building',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='lab',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
